Iter
nextlag/gomart pull request #21
Opened 2024-02-06 10:55 UTC by nextlag

2024-02-12 23:43 UTC, avhitrov requested changes
Оформление задания на проверку оформлено неверно, ссылка ведет не на конкретный ПР, а прямо на весь список, вроде как на выбор. Обычно это является формальным поводом отправить проект на доработку, не читая.

Тем не менее просмотрел по диагонали, добравшись до usecase; до структур данных пока не дошел, но есть достаточно оснований вернуть на доработку с общими указаниями:
1. Невозможно понять, какие стадии разработки покрывает данный ПР. Очевидно, что реализовано не все ТЗ, но список реализованных фич и ToDo необходимо перечислить хотя бы в комментариях к ПР.
2. Очень слабое документирование кода. Нет ни `*.md` файлов, в которых прописано задание и реализованные фичи, ни вступлений к модулям, не везде даны описания структур и полей структур. Комментарии в коде сделаны скорее "для себя". Но это дипломная работа и она требует документации "по полной программе".
3. Именование структур несколько обескураживает. Например `entity.Orders` символом `s` на конце указывает на то, что в структуре будут храниться какие-то списки или иные массивы данных. На деле структура описывает один единственный заказ.
4. Отсутствует graceful shutdown. При остановке сервера процедура Sync с большой вероятностью поломается где-то посередине обновления статуса, оставив в БД неконсистентные данные.
5. Не увидел транзакционности при работе с БД. Любая система, оперирующая деньгами обязана при внесении данных в несколько таблиц давать однозначный результат - либо все записалось, либо все откатилось.

Пока так.

2024-02-12 23:43 UTC, avhitrov commented on internal/controllers/register.go
> +func (c Controller) Register(w http.ResponseWriter, r *http.Request) {
```suggestion
func (c *Controller) Register(w http.ResponseWriter, r *http.Request) {
```
В принципе, можно оставить value receiver, но при большом количестве обращений при вызове каждой функции структура Controller будет копироваться и съедать память.

2024-02-12 23:43 UTC, avhitrov commented on internal/mw/logger/slogger.go
> +// }
Не следует в git хранить закомментированные куски кода, да еще и в дипломном проекте. При необходимости на них всегда можно откатиться.

2024-02-12 23:43 UTC, avhitrov commented on internal/usecase/accrual.go
> +		}
При получении, например, кода 200 и статуса `PROCESSING` функция будет долбить эндпоинт со скоростью пулемета. Как минимум, необходимо сделать time.Sleep перед выходом на следующую итерацию, а лучше сделать явное перечисление и обработку всех статусов ответа и корнер-кейсов. 

По виду функции без лежащего под рукой ТЗ непонятно, что какой ответ означает, и какая реакция на него предполагается. Но это уже касается общих рекомендаций по документированию представленного кода.

2024-02-12 23:43 UTC, avhitrov commented on internal/usecase/accrual.go
> +			time.Sleep(3 * time.Second)
В теле ответа есть указание, когда приходить в следующий раз. Почему 3 секунды?

2024-02-12 23:43 UTC, avhitrov commented on internal/usecase/accrual.go
> +			time.Sleep(1 * time.Second)
Если дернуть данную функцию с номером заказа, который соответствует коду Луна, но при этом в принципе не существует в системе, данная функция будет крутиться вечно. Используя нехитрую методологию можно будет зафлудить и положить не только данный сервис, но и тот, который данная функция опрашивает.

2024-02-22 13:01 UTC, nextlag commented
список реализованных фич:
1. POST /api/user/register — регистрация пользователя;
2. POST /api/user/login — аутентификация пользователя;
3. POST /api/user/orders — загрузка пользователем номера заказа для расчёта;
4. GET /api/user/orders — получение списка загруженных пользователем номеров заказов, статусов их обработки и информации о начислениях;
5. GET /api/user/balance — получение текущего баланса счёта баллов лояльности пользователя;
6. POST /api/user/balance/withdraw — запрос на списание баллов с накопительного счёта в счёт оплаты нового заказа;
7. GET /api/user/withdrawals — получение информации о выводе средств с накопительного счёта пользователем.
8. Взаимодействие с системой расчёта начислений баллов лояльности
9.  Тестирование хендлеров (регистрации и аутентификации)

2024-02-26 23:52 UTC, avhitrov requested changes
Проведена блестящая работа по документированию. На этом достижения закончились.
Все еще нет мягкого шатдауна. Отсутствует транзакционность при выполнении запросов.

2024-02-26 23:52 UTC, avhitrov commented on internal/controllers/register.go
> +	w.Write([]byte(cookie))
Не очень понятно, зачем класть куку в тело ответа. Или это просто отладка?

2024-02-26 23:52 UTC, avhitrov commented on internal/usecase/accrual.go
> +				return orderUpdate, fmt.Errorf("internal server error in accrual system: %v", err)
Во всех этих трех кейсах err == nil. Потому что с err != nil мы сваливаем из функции на 61 строке. Это не стоппер, если ничего серьезного далее по коду не найду, то аппрувну, как есть. Но вообще здесь конструкцию можно смело заменить на errors.New, так как во всех случаях создается и возвращается свеженькая собственная ошибка.

2024-02-26 23:52 UTC, avhitrov commented on internal/usecase/accrual.go
> +			Rows(ctx)
Имеет смысл лимитировать размер батча, этот лимит заодно можно использовать для инициализации allOrders, при большом количестве скопившихся заказов (или при горизонтальном масштабировании) функция не попытается захватить сразу все записи из базы, не затупит и не пропустит следующий tick.

При одновременном процессинге сразу несколькими воркерами желательно делать не select, а update с возвращением всех полей. И при этом апдейте отмечать статусом (например, 'SYNCING') или в отдельном поле, что запись на проверке. После завершения обработки батча, менять статус обратно или на новый полученный. Но я не знаю, позволяет ли выбранный фреймворк подобные штуки.

2024-02-26 23:52 UTC, avhitrov commented on internal/usecase/accrual.go
> +				return err
А куда мы отсюда выходим? Это же служебная горутина. Получается, любой таймаут к постгресу - и весь сервер падает. Так быть не должно.

2024-02-26 23:52 UTC, avhitrov commented on internal/usecase/accrual.go
> +				return err
А вот здесь как-то совсем неловко ставить жизнь своего сервера в зависимость от доступности черного ящика. Не буду указывать на каждый return по ошибке, скажу за всю функцию. Она может завершить свою работу только по сигналу от main. И никак иначе. Но по сигналу от main она должна это сделать максимально быстро и аккуратно.

2024-02-26 23:52 UTC, avhitrov commented on internal/usecase/accrual.go
> +	for range ticker.C {
В данном цикле необходимо так же, как и в GetAccrual, слушать канал stop (или контекст приложения), иначе graceful shutdown не получится. Нужен не `for range`, а `for - select` с прослушиванием stop-канала.

2024-02-26 23:52 UTC, avhitrov commented on internal/usecase/accrual.go
> +	ticker := time.NewTicker(tick)
defer ticker.Stop()

2024-02-26 23:52 UTC, avhitrov commented on cmd/gophermart/main.go
> +	log.Info("server stopped")
Отсутствует ожидание завершения работы горутин. Как минимум, в каждую необходимо пробросить WaitGroup, а после получения сигнала от OS, 
1. Закрыть канал `stop`
2. Дать http-серверу сигнал на остановку
3. Дождаться завершения обеих горутин (wg.Wait())

2024-02-26 23:52 UTC, avhitrov commented on internal/usecase/accrual.go
> +	}
Обе функции должны быть объединены транзакцией. Обновилась одна таблица - обновилась другая. Произошел сбой в одной таблице - откатились все изменения. Не вижу транзакционной обвязки.

2024-02-26 23:52 UTC, avhitrov commented on internal/usecase/repository.go
> +	db := bun.NewDB(uc.DB, pgdialect.New())
Я не залезал глубоко в потроха bun, но разве NewDB необходимо делать не один раз на старте приложения? Это же просто обвязка над драйвером. А здесь получается странноватая схема: мы открываем транзакцию, потом за рамками этой транзакции выполняем sql запрос, а потом закрываем пустую транзакцию.

https://pkg.go.dev/database/sql#Tx
```
The statements prepared for a transaction by calling the transaction's [Tx.Prepare](https://pkg.go.dev/database/sql#Tx.Prepare) or [Tx.Stmt](https://pkg.go.dev/database/sql#Tx.Stmt) methods are closed by the call to [Tx.Commit](https://pkg.go.dev/database/sql#Tx.Commit) or [Tx.Rollback](https://pkg.go.dev/database/sql#Tx.Rollback).
```

2024-02-26 23:54 UTC, avhitrov requested changes

2024-02-26 23:54 UTC, avhitrov commented on internal/controllers/.DS_Store
Необходимо удалить

2024-02-29 12:26 UTC, nextlag commented
Андрей, посмотрите пожалуйста еще - правильно ли я реализовал чистую архитектуру?
У меня центральный слой entity, к нему обращается только usecase. Меня интересует такой аспект:

func (uc *UseCase) DoRegister(ctx context.Context, login, password string, _ *http.Request) error {
	err := uc.repo.Register(ctx, login, password)
	return err
}
Здесь для каждого метода Usecase я создаю параллельно метод controllers. 

Когда я пробовал обратиться к объектам usecase через метод:
func (uc *UseCase) Do() *UseCase {
	return uc
}
- я ловлю панику из-за nil pointer, пока не понял, как пофиксить это

2024-03-04 21:42 UTC, avhitrov commented
Я считаю, что 
```
func (uc *UseCase) DoRegister(ctx context.Context, login, password string, _ *http.Request) error {
    err := uc.repo.Register(ctx, login, password)
    return err
}
```
является максимально правильным вариантом. В этом случае логика, отвечающая за взаимодействие с хранилищем, падает на слой repo, а условно бизнес-логика остается в в UseCase. Хранилище при этом легко заменить, просто подсунув другой пакет, реализующий тот же интерфейс.

Вариант `c.uc.Do().Register(...)` мне кажется более чем странной конструкцией, так как c.uc уже возвращает ссылку на объект, который пытается вернуть Do(). Оверинженеринг в чистом виде. В рамках борьбы с паникой можно поисследовать, почему падает по панике, обвешав конструкцию проверками `if [часть системы вызовов] == nil`. И посмотреть, на каком этапе разыменования возникает nil.

2024-03-04 22:51 UTC, avhitrov requested changes
Транзакционность и graceful shutdown ok, остались вопросы к использованию контекста.

Я предлагаю взять 1-1, за полчаса я смогу быстро охватить все возникшие вопросы и снять замеченное мной недопонимание работы отдельных компонент и концепций.

2024-03-04 22:51 UTC, avhitrov commented on internal/controllers/authentication.go
> +	log := l.L(c.ctx)
В рамках обработки http-запросов необходимо использовать контекст самого запроса - r.Context(), так как именно по нему бывает необходимо разорвать http-подзапрос или sql-запрос. Протухание этого контекста всегда связано с отказом пользователя от завершения запроса или разрывом соединения. Контекст приложения c.ctx должен охватывать работу подсистем приложения (http-сервер, воркеры) и передавать сигнал остановки именно в них.

В отношении логгера я не знаю, для чего в нем нужен контекст (не смотрел пока в потроха). Возможно, ему норм будет скормить контекст приложения. Но вот для всех остальных вызовов необходим именно r.Context().

Это замечание касается всех http-хендлеров.

2024-03-04 22:51 UTC, avhitrov commented on internal/controllers/register.go
> +	user := c.uc.Do().GetEntity()
```suggestion
	user := c.uc.GetEntity()
```
uc и так является ссылкой на объект, нет необходимости возвращать копию ссылки на него же.

2024-03-04 22:51 UTC, avhitrov commented on internal/usecase/accrual.go
> +	defer cancel()
Контекст приходит в функцию снаружи, нет необходимости его здесь создавать.

2024-03-04 22:51 UTC, avhitrov commented on internal/usecase/accrual.go
> +			cancel()
Канселить здесь контекст тоже нет никакой необходимости, так как при попадании в эту часть вычислительного процесса остановка контекста уже ни к чему не приведет. Все остальные ветки отработали, рвать нечего.

2024-03-04 22:51 UTC, avhitrov commented on internal/usecase/accrual.go
> +					cancel()
Канселить здесь контекст тоже нет никакой необходимости, так как при попадании в эту часть вычислительного процесса остановка контекста уже ни к чему не приведет. Нет никаких работающих в фоне процессов, которые этот контекст мог бы остановить.

2024-03-06 18:58 UTC, avhitrov approved these changes
Все основные исправления внесены. Мои поздравления!

2024-03-07 07:36 UTC, merged